# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Artist.create!(name: 'Kanye West', genre: 'Hip Hop', bio: 'Kanye West is an American rapper, singer, songwriter, record producer, entrepreneur and fashion designer.')
Artist.create!(name: 'Ed Sheeran', genre: 'Folk', bio: 'Ed Sheeran is an English singer, songwriter, guitarist, record producer, and actor.')
Artist.create!(name: 'Taylor Swift', genre: 'Pop', bio: 'Taylor Swift is an American singer-songwriter.')
Artist.create!(name: 'Eminem', genre: 'Rap', bio: 'Marshall Mathers known professionally as Eminem (often stylized as EMINƎM), is an American rapper, songwriter, record producer, record executive, and actor.')
Artist.create!(name: 'Drake', genre: 'R&b', bio: 'Drake is a Canadian rapper, singer, songwriter, record producer, and actor.')
Artist.create!(name: 'The Weeknd', genre: 'R&b', bio: 'Abel Tesfaye, known by his stage name The Weeknd, is a Canadian singer, songwriter, and record producer.')
Artist.create!(name: 'Ariana Grande', genre: 'Pop', bio: 'Ariana Grande is an American singer and actress. ')
Artist.create!(name: 'Migos', genre: 'Hip Hop', bio: 'Migos is an American hip hop trio from Lawrenceville, Georgia, founded in 2008.')
Artist.create!(name: 'Imagine Dragons', genre: 'Pop Rock', bio: 'Imagine Dragons is an American pop rock band from Las Vegas, Nevada.')
Artist.create!(name: 'Beyonce', genre: 'R&b', bio: 'Beyonce is an American singer, songwriter, performer, and actress.')
Artist.create!(name: 'Jay-Z', genre: 'Rap', bio: 'Shawn Carter known professionally as Jay-Z is an American rapper, songwriter, record producer, and entrepreneur.')
Artist.create!(name: 'Bruno Mars', genre: 'Funk', bio: 'Peter Hernandez known professionally as Bruno Mars, is an American singer-songwriter, multi-instrumentalist, record producer, and dancer.')
Artist.create!(name: 'The Chainsmokers', genre: 'EDM', bio: 'The Chainsmoker sare an American DJ and production duo.')
Artist.create!(name: 'Coldplay', genre: 'Alt Rock', bio: 'Coldplay are a British rock band formed in 1996.')
Artist.create!(name: 'Maroon 5', genre: 'Pop Rock', bio: 'Maroon 5 is an American pop rock band from Los Angeles, California.')
Artist.create!(name: 'Katy Perry', genre: 'Pop', bio: 'Katy Perry is an American singer, songwriter, and television personality.')
Artist.create!(name: 'Florida Georgia Line', genre: 'Country', bio: 'Florida Georgia Line is an American country music duo.')
Artist.create!(name: 'Lady Gaga', genre: 'Pop', bio: 'Lady Gaga is an American singer, songwriter, and actress.')
Artist.create!(name: 'Elton John', genre: 'Pop Rock', bio: 'Elton John is an English singer, pianist, and composer.')
Artist.create!(name: 'Metallica', genre: 'Heavy Metal', bio: 'Metallica is an American heavy metal band from Los Angeles, California.')


Venue.create!(name: "Grand Star Jazz Club", location: "NYC", capacity: 300)
Venue.create!(name: "The End", location: "Brooklyn", capacity: 200)
Venue.create!(name: "Blackbird Ordinary", location: "New Jersey", capacity: 400)
Venue.create!(name: "Lincoln Hall", location: "Boston", capacity: 507)
Venue.create!(name: "Santos Party House", location: "NYC", capacity: 480)

Fan.create!(name: 'Billy', drunk: true, balance: 500, age: 19, favorite_artist: 'Green Day', username: '1', password: '1234')
# Fan.create!(name: 'Sally', drunk: false, balance: 1000, age: 28, favorite_artist: 'u2')
# Fan.create!(name: 'Teddy', drunk: false, balance: 100, age: 20, favorite_artist: 'kendrick lamar')
# Fan.create!(name: 'Mary', drunk: true, balance: 400, age: 21, favorite_artist: 'bone thugs n harmony')
# Fan.create!(name: 'Freddy', drunk: false, balance: 2000, age: 32, favorite_artist: 'ludwig van beethoven')
# Fan.create!(name: 'Tammy', drunk: true, balance: 2500, age: 38, favorite_artist: 'frank sinatra')

Concert.create!(artist_id: 1, venue_id: 1, date: '01-01-2018', price: 120)
Concert.create!(artist_id: 1, venue_id: 2, date: '01-01-2018', price: 40)
Concert.create!(artist_id: 1, venue_id: 3, date: '01-01-2018', price: 80)
Concert.create!(artist_id: 2, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 2, venue_id: 5, date: '01-01-2018', price: 50)
Concert.create!(artist_id: 2, venue_id: 1, date: '01-01-2018', price: 180)
Concert.create!(artist_id: 3, venue_id: 2, date: '01-01-2018', price: 100)
Concert.create!(artist_id: 3, venue_id: 3, date: '01-01-2018', price: 40)
Concert.create!(artist_id: 3, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 4, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 4, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 4, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 5, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 5, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 5, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 6, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 6, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 6, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 7, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 7, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 7, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 8, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 8, venue_id: 2, date: '01-01-2018', price: 80)
Concert.create!(artist_id: 8, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 9, venue_id: 2, date: '01-01-2018', price: 50)
Concert.create!(artist_id: 9, venue_id: 4, date: '01-01-2018', price: 180)
Concert.create!(artist_id: 9, venue_id: 1, date: '01-01-2018', price: 100)
Concert.create!(artist_id: 10, venue_id: 1, date: '01-01-2018', price: 40)
Concert.create!(artist_id: 10, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 10, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 11, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 11, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 11, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 11, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 12, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 12, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 12, venue_id: 4, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 12, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 13, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 13, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 13, venue_id: 3, date: '01-01-2018', price: 120)
Concert.create!(artist_id: 13, venue_id: 4, date: '01-01-2018', price: 40)
Concert.create!(artist_id: 13, venue_id: 5, date: '01-01-2018', price: 80)
Concert.create!(artist_id: 14, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 14, venue_id: 2, date: '01-01-2018', price: 50)
Concert.create!(artist_id: 14, venue_id: 3, date: '01-01-2018', price: 180)
Concert.create!(artist_id: 14, venue_id: 4, date: '01-01-2018', price: 100)
Concert.create!(artist_id: 14, venue_id: 5, date: '01-01-2018', price: 40)
Concert.create!(artist_id: 15, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 15, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 15, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 16, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 17, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 17, venue_id: 5, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 18, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 19, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 20, venue_id: 1, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 20, venue_id: 2, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 20, venue_id: 3, date: '01-01-2018', price: 60)
Concert.create!(artist_id: 20, venue_id: 4, date: '01-01-2018', price: 60)

# Ticket.create!(fan_id: 1, concert_id: 1)
# Ticket.create!(fan_id: 5, concert_id: 2)
# Ticket.create!(fan_id: 3, concert_id: 3)
# Ticket.create!(fan_id: 6, concert_id: 4)
# Ticket.create!(fan_id: 2, concert_id: 5)
# Ticket.create!(fan_id: 4, concert_id: 6)
# Ticket.create!(fan_id: 1, concert_id: 7)
# Ticket.create!(fan_id: 6, concert_id: 8)
# Ticket.create!(fan_id: 5, concert_id: 9)

puts "It worked!"
